import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FavoriteProvider } from "./components/FavoriteContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Loja Virtual",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <FavoriteProvider>{children}</FavoriteProvider>
      </body>
    </html>
  );
}
